Fix #8 - Mostrando parâmetros dos endpoints
odufrn/odufrn-api-py pull request #18
Opened 2019-10-08 18:38 UTC by JohnAzedo

# Pull Request
A funcionalidade `print_resource_endpoints` deveria mostrar também os parâmetros que o endpoint oferece.

- **Issues vinculadas**:
  - #8  - Fix

## Principais locais de modificação
- `print_resource_endpoints` na classe `UfrnApi`
- Adição do método `__url__` na classe `UfrnApi`

2019-10-08 18:44 UTC, nymarya requested changes

2019-10-08 18:44 UTC, nymarya commented on odufrn_api_py/odufrn_api_py.py
> +            Nome do recurso utiliado para recuperar
utilizado

2019-10-08 18:44 UTC, nymarya commented on odufrn_api_py/odufrn_api_py.py
> +            a url desse memso recurso.
mesmo

2019-10-08 18:46 UTC, nymarya approved these changes

2019-10-10 19:37 UTC, itepifanio approved these changes

2019-10-10 19:37 UTC, merged